[supervisord]
nodaemon=true
user=root
logfile=/tmp/log/supervisord.log
pidfile=/tmp/run/supervisord.pid

[program:openvscode]
command=/usr/local/code-server/bin/code-server --bind-addr 0.0.0.0:3000 --auth none --disable-telemetry --disable-update-check --disable-workspace-trust
user=$USER_NAME
environment=HOME="/home/$USER_NAME",USER="$USER_NAME",DISPLAY=":10.0",XDG_RUNTIME_DIR="/run/user/$USER_UID"
priority=60
autorestart=true
